
package br.com.card_editor.ejb.system_user;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SystemUserService", targetNamespace = "http://system_user.ejb.card_editor.com.br/", wsdlLocation = "http://192.168.0.11:7004/SystemUserServiceImpl/SystemUserService?WSDL")
public class SystemUserService
    extends Service
{

    private final static URL SYSTEMUSERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.card_editor.ejb.system_user.SystemUserService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.card_editor.ejb.system_user.SystemUserService.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.0.11:7004/SystemUserServiceImpl/SystemUserService?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.0.11:7004/SystemUserServiceImpl/SystemUserService?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SYSTEMUSERSERVICE_WSDL_LOCATION = url;
    }

    public SystemUserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SystemUserService() {
        super(SYSTEMUSERSERVICE_WSDL_LOCATION, new QName("http://system_user.ejb.card_editor.com.br/", "SystemUserService"));
    }

    /**
     * 
     * @return
     *     returns SystemUserServiceImpl
     */
    @WebEndpoint(name = "SystemUserServiceImplPort")
    public SystemUserServiceImpl getSystemUserServiceImplPort() {
        return super.getPort(new QName("http://system_user.ejb.card_editor.com.br/", "SystemUserServiceImplPort"), SystemUserServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SystemUserServiceImpl
     */
    @WebEndpoint(name = "SystemUserServiceImplPort")
    public SystemUserServiceImpl getSystemUserServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://system_user.ejb.card_editor.com.br/", "SystemUserServiceImplPort"), SystemUserServiceImpl.class, features);
    }

}
