
package br.com.card_editor.ejb.system_user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SystemUserServiceImpl", targetNamespace = "http://system_user.ejb.card_editor.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SystemUserServiceImpl {


    /**
     * 
     * @param systemUser
     */
    @WebMethod
    @RequestWrapper(localName = "cadastrarUsuario", targetNamespace = "http://system_user.ejb.card_editor.com.br/", className = "br.com.card_editor.ejb.system_user.CadastrarUsuario")
    @ResponseWrapper(localName = "cadastrarUsuarioResponse", targetNamespace = "http://system_user.ejb.card_editor.com.br/", className = "br.com.card_editor.ejb.system_user.CadastrarUsuarioResponse")
    public void cadastrarUsuario(
        @WebParam(name = "systemUser", targetNamespace = "")
        SystemUser systemUser);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "alterarUsuario", targetNamespace = "http://system_user.ejb.card_editor.com.br/", className = "br.com.card_editor.ejb.system_user.AlterarUsuario")
    @ResponseWrapper(localName = "alterarUsuarioResponse", targetNamespace = "http://system_user.ejb.card_editor.com.br/", className = "br.com.card_editor.ejb.system_user.AlterarUsuarioResponse")
    public void alterarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        SystemUser arg0);

    /**
     * 
     * @param systemUser
     */
    @WebMethod
    @RequestWrapper(localName = "excluirUsuario", targetNamespace = "http://system_user.ejb.card_editor.com.br/", className = "br.com.card_editor.ejb.system_user.ExcluirUsuario")
    @ResponseWrapper(localName = "excluirUsuarioResponse", targetNamespace = "http://system_user.ejb.card_editor.com.br/", className = "br.com.card_editor.ejb.system_user.ExcluirUsuarioResponse")
    public void excluirUsuario(
        @WebParam(name = "systemUser", targetNamespace = "")
        SystemUser systemUser);

}
