
package br.com.card_editor.player;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PlayerServiceImpl", targetNamespace = "http://player.card_editor.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PlayerServiceImpl {


    /**
     * 
     * @param player
     */
    @WebMethod
    @RequestWrapper(localName = "excluirPlayer", targetNamespace = "http://player.card_editor.com.br/", className = "br.com.card_editor.player.ExcluirPlayer")
    @ResponseWrapper(localName = "excluirPlayerResponse", targetNamespace = "http://player.card_editor.com.br/", className = "br.com.card_editor.player.ExcluirPlayerResponse")
    public void excluirPlayer(
        @WebParam(name = "player", targetNamespace = "")
        Player player);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "alterarPlayer", targetNamespace = "http://player.card_editor.com.br/", className = "br.com.card_editor.player.AlterarPlayer")
    @ResponseWrapper(localName = "alterarPlayerResponse", targetNamespace = "http://player.card_editor.com.br/", className = "br.com.card_editor.player.AlterarPlayerResponse")
    public void alterarPlayer(
        @WebParam(name = "arg0", targetNamespace = "")
        Player arg0);

    /**
     * 
     * @param player
     */
    @WebMethod
    @RequestWrapper(localName = "cadastrarPlayer", targetNamespace = "http://player.card_editor.com.br/", className = "br.com.card_editor.player.CadastrarPlayer")
    @ResponseWrapper(localName = "cadastrarPlayerResponse", targetNamespace = "http://player.card_editor.com.br/", className = "br.com.card_editor.player.CadastrarPlayerResponse")
    public void cadastrarPlayer(
        @WebParam(name = "player", targetNamespace = "")
        Player player);

}
