
package br.com.card_editor.player;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PlayerService", targetNamespace = "http://player.card_editor.com.br/", wsdlLocation = "http://192.168.56.1:7004/PlayerServiceImpl/PlayerService?WSDL")
public class PlayerService
    extends Service
{

    private final static URL PLAYERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.card_editor.player.PlayerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.card_editor.player.PlayerService.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.56.1:7004/PlayerServiceImpl/PlayerService?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.56.1:7004/PlayerServiceImpl/PlayerService?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PLAYERSERVICE_WSDL_LOCATION = url;
    }

    public PlayerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlayerService() {
        super(PLAYERSERVICE_WSDL_LOCATION, new QName("http://player.card_editor.com.br/", "PlayerService"));
    }

    /**
     * 
     * @return
     *     returns PlayerServiceImpl
     */
    @WebEndpoint(name = "PlayerServiceImplPort")
    public PlayerServiceImpl getPlayerServiceImplPort() {
        return super.getPort(new QName("http://player.card_editor.com.br/", "PlayerServiceImplPort"), PlayerServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PlayerServiceImpl
     */
    @WebEndpoint(name = "PlayerServiceImplPort")
    public PlayerServiceImpl getPlayerServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://player.card_editor.com.br/", "PlayerServiceImplPort"), PlayerServiceImpl.class, features);
    }

}
