
package br.com.card_editor.ejb.card;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CardServiceImpl", targetNamespace = "http://card.ejb.card_editor.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CardServiceImpl {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "uploadCard", targetNamespace = "http://card.ejb.card_editor.com.br/", className = "br.com.card_editor.ejb.card.UploadCard")
    @ResponseWrapper(localName = "uploadCardResponse", targetNamespace = "http://card.ejb.card_editor.com.br/", className = "br.com.card_editor.ejb.card.UploadCardResponse")
    public void uploadCard(
        @WebParam(name = "arg0", targetNamespace = "")
        InSalvarCard arg0);

}
